project:
  type: website
  output-dir: docs
  resources:
    - images/lescodex-logo.png # for light mode
    - images/lescodex-logo-white.png # for dark mode
    - downloads/capstone/capstone.zip
  render:
    - index.qmd
    - "Introduction to R/*.qmd"
    - "Python Tutorials/*.qmd"
    - "Error Bypass Atlas/*.qmd"
    - "Capstone Analysis/*.qmd"
    - about.qmd

website:
  title: |
    <a href="index.html" aria-label="Les Codex Home">
      <img id="site-logo" src="images/lescodex-logo.png" alt="Les Codex" style="height:50px;">
    </a>
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "R Tutorials"
        menu:
          - text: "Introduction to R"
            href: Introduction to R/index.qmd
          - text: "Key Packages"
            href: Introduction to R/packages.qmd
      - text: "Python Tutorials"
        menu:
          - text: "Getting Started"
            href: Python Tutorials/index.qmd
          - text: "Data Science Stack"
            href: Python Tutorials/packages.qmd
      - text: "Error Bypass"
        href: Error Bypass Atlas/index.qmd
      - text: "Capstone Analysis"
        href: Capstone Analysis/index.qmd
    right:
      - text: "About"
        href: about.qmd

format:
  html:
    theme: 
      light: default
      dark:  dark
    css:
    - styles/logo-switch.css
    - styles/custom.css
    toc: true

