# ─── _quarto.yml ────────────────────────────────────────────────────────────────

project:
  type: website
  output-dir: docs

  # ─── Make sure Quarto copies these into docs/images/ ─────────────────────────────
  resources:
    - images/lescodex-logo.png
    - images/lescodex-logo-white.png

website:
  # ─── Embed only the <img> tag; no “Les Codex” text beside it ───────────────────
  title: |
    <a href="index.html" aria-label="Les Codex Home">
      <img
        id="site-logo"
        src="images/lescodex-logo.png"
        alt="Les Codex"
        style="height:90px;"
      >
    </a>

  navbar:
    left:
      - text: "R Tutorials"
        menu:
          - text: "Getting Started"
            href: Introduction to R/index.qmd
          - text: "Key Packages"
            href: Introduction to R/packages.qmd
      - text: "Python Tutorials"
        menu:
          - text: "Getting Started"
            href: Python Tutorials/index.qmd
          - text: "Data Science Stack"
            href: Python Tutorials/packages.qmd
      - text: "Error Bypass"
        href: Error Bypass Atlas/index.qmd
      - text: "Capstone Analysis"
        href: Capstone Analysis/index.qmd
    right:
      - text: "About"
        href: about.qmd

format:
  html:
    # ─── Let Quarto handle light/dark switching for general page styles ─────────────
    theme:
      light: default
      dark:  dark

    css:
      # ─── 1) Swap logo images based on light/dark
      - styles/logo-switch.css
      # ─── 2) Override everything else: code colors, fonts, navbar, etc.
      - styles/custom.css

    toc: true

# ───────────────────────────────────────────────────────────────────────────────────
