project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - "Introduction to R/*.qmd"
    # - python/*.qmd
    - about.qmd

website:
  title: "Les Codex"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Introduction to R"
        href: Introduction to R/index.qmd
      # - text: "Python"
        # href: python/index.qmd
    right:
      - text: "About"
        href: about.qmd

format:
  html:
    theme: default
    css: styles/minimal.css
    toc: true
