project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - "Introduction to R/*.qmd"
    - "Python Tutorials/*.qmd"
    - "Error Bypass Atlas/*.qmd"
    - "Capstone Analysis/*.qmd"
    - about.qmd

website:
  title: "Les Codex"
  logo: images/lescodex-logo.png
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "R Tutorials"
        menu:
          - text: "Introduction to R"
            href: Introduction to R/index.qmd
          - text: "Key Packages"
            href: Introduction to R/packages.qmd
      - text: "Python Tutorials"
        menu:
          - text: "Getting Started"
            href: Python Tutorials/index.qmd
          - text: "Data Science Stack"
            href: Python Tutorials/packages.qmd
      - text: "Error Bypass"
        href: Error Bypass Atlas/index.qmd
      - text: "Capstone Analysis"
        href: Capstone Analysis/index.qmd
    right:
      - text: "About"
        href: about.qmd

format:
  html:
    theme: default
    css: styles/minimal.css
    toc: true

